customer_support_tickets:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /shared/duckdb/support.duckdb
      threads: 4
      # Agregamos esto para que dbt pueda manejar formatos modernos y fechas
      extensions:
        - icu
        - parquet
      # Forzamos a que dbt trabaje en un esquema limpio
      schema: main 
