version: 2

models:
  - name: stg_tickets_200k
    description: "Modelo de staging de 200k tickets"
    columns:
      - name: ticket_id
        tests:
          - not_null:
              config:
                severity: warn
          - unique:
              config:
                severity: warn
      - name: priority
        tests:
          - accepted_values:
              # Sintaxis moderna para evitar el Deprecation Warning
              values: ['low', 'medium', 'high', 'critical']
              config:
                # Si querés que el pipeline sea perfecto, subilo a 'error' 
                # o dejalo en 'warn' si esos 4 valores no te molestan.
                severity: warn 

  - name: stg_tickets
    description: "Modelo de staging principal"
    columns:
      - name: ticket_id
        tests:
          - not_null
          - unique

  - name: stg_users
    description: "Modelo de staging para usuarios"
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
