name: 'customer_support_tickets'
version: '1.0.0'
config-version: 2
profile: 'customer_support_tickets'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  customer_support_tickets:
    +materialized: table
    # No pongas +schema acá para que dbt use el esquema por defecto del profile (main)
    staging:
      +materialized: view
    marts:
      +materialized: table
      
seeds:
  customer_support_tickets:
    +schema: main
    +column_types:
      # IDs como texto para que acepten cualquier formato
      "Ticket ID": varchar
      "Customer Email": varchar
      
      # Métricas como DOUBLE para que acepten decimales siempre
      "Customer Satisfaction Rating": double
      "First Response Time": double
      "Time to Resolution": double
      
      # Fechas para que no se confunda con texto
      "Date of Purchase": date
