[server]
port = 8501
address = "0.0.0.0"
headless = true
runOnSave = false

[theme]
primaryColor = "#636EFA"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1C2333"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false